server:
  port: 85
  servlet:
    context-path: /Client
spring:
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
    producer:
      bootstrap-servers: 127.0.0.1:9092
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3307/doanspringboot
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    server:
      error:
        path=/error: error.whitelabel.enabled=false

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 659055384731-ud2outcjoo6ieqqt4bod38t6paf5pnmc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1164522987493780
            client-secret: eb9622abbe33a7a7de6951fccfe81cae
            scope:
              - email
              - public_profile

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: trangdc.103@gmail.com
#    password: hyizbfeqjbxxwnpc
#    smtp :
#      debug: true
#  properties:
#         mail:
#           smtp:
#             auth: true
#             starttls:
#               enable: true
#               required: true
#             connectiontimeout : 5000
#             timeout : 5000
#             writetimeout: 5000



  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: trangdc.103@gmail.com
    password: hyizbfeqjbxxwnpc
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

